// ---------------------------------------------------------------------------
// Generated by scripts/gen-db-types.mjs from supabase/migrations/*.sql
// DO NOT EDIT BY HAND — run `npm run gen:types` after changing a migration.
// ---------------------------------------------------------------------------

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type UserRole = 'student' | 'teacher' | 'alumni' | 'guardian' | 'admin';
export type AppStatus = 'pending' | 'under_review' | 'approved' | 'rejected';
export type PostType = 'post' | 'notice' | 'question' | 'event' | 'achievement' | 'resource';
export type PostStatus = 'published' | 'hidden' | 'deleted';
export type NotificationType = 'approval_update' | 'new_follower' | 'like' | 'comment' | 'reply' | 'mention' | 'message' | 'message_request' | 'notice' | 'system' | 'promotion' | 'report_update' | 'badge' | 'year_update';
export type ReportStatus = 'open' | 'reviewing' | 'resolved' | 'dismissed';
export type ConvKind = 'dm' | 'group';
export type MemberRole = 'owner' | 'admin' | 'member';
export type OutboxStatus = 'pending' | 'sent' | 'failed';
export type ChildLinkStatus = 'pending' | 'approved' | 'rejected';

export type ProfilesRow = {
  id: string;
  handle: string;
  full_name: string;
  email: string;
  role: UserRole;
  status: AppStatus;
  avatar_url: string | null;
  banner_url: string | null;
  bio: string | null;
  website_url: string | null;
  location_text: string | null;
  lat: number | null;
  lng: number | null;
  location_consent: boolean | null;
  notif_consent: boolean | null;
  theme_accent: string | null;
  pronouns: string | null;
  verified: boolean | null;
  onboarded: boolean | null;
  interests: string[] | null;
  show_dwell: boolean | null;
  locale: string | null;
  created_at: string | null;
  updated_at: string | null;
  fts: string | null;
};

export type ReservedHandlesRow = {
  handle: string;
};

export type AcademicsRow = {
  user_id: string;
  current_class: number;
  section: string | null;
  roll: number | null;
  academic_year: number;
  nid_or_brc: string | null;
  dob: string | null;
  needs_year_update: boolean | null;
  graduated: boolean | null;
  history: Json | null;
};

export type TeacherInfoRow = {
  user_id: string;
  experience_years: number | null;
  teaches: Json | null;
  department: string | null;
};

export type AlumniInfoRow = {
  user_id: string;
  current_institution: string | null;
  current_class: string | null;
  old_class: number | null;
  old_section: string | null;
  old_roll: number | null;
  passing_year: number | null;
  notes: string | null;
};

export type GuardianInfoRow = {
  user_id: string;
  phone: string | null;
  relationship: string;
  occupation: string | null;
};

export type GuardianChildrenRow = {
  guardian_id: string;
  child_id: string;
  status: ChildLinkStatus;
  created_at: string | null;
};

export type ClassSectionsRow = {
  academic_year: number;
  class_no: number;
  section: string;
};

export type RegistrationApplicationsRow = {
  id: string;
  applicant_id: string | null;
  role: UserRole;
  payload: Json;
  status: AppStatus;
  attempt: number | null;
  submitted_at: string | null;
  decided_at: string | null;
  decided_by: string | null;
  reason: string | null;
};

export type ApprovalEventsRow = {
  id: string;
  application_id: string | null;
  actor_id: string | null;
  action: string;
  note: string | null;
  ts: string | null;
};

export type SecureDocumentsRow = {
  id: string;
  owner_id: string | null;
  purpose: string;
  mime_original: string;
  sha256: string;
  svg_text: string;
  size_bytes: number;
  created_at: string | null;
};

export type FollowsRow = {
  follower_id: string;
  following_id: string;
  created_at: string | null;
};

export type BlocksRow = {
  blocker_id: string;
  blocked_id: string;
  created_at: string | null;
};

export type MutedUsersRow = {
  muter_id: string;
  muted_id: string;
  created_at: string | null;
};

export type HiddenPostsRow = {
  user_id: string;
  post_id: string;
  created_at: string | null;
};

export type PostsRow = {
  id: string;
  author_id: string | null;
  type: PostType;
  title: string | null;
  body_md: string | null;
  body_text: string | null;
  slug: string | null;
  class_tag: number | null;
  section_tag: string | null;
  location: string | null;
  language: string | null;
  comments_enabled: boolean | null;
  sensitive: boolean | null;
  pinned: boolean | null;
  status: PostStatus;
  likes_count: number | null;
  comments_count: number | null;
  shares_count: number | null;
  views_count: number | null;
  impressions_count: number | null;
  hashtags: string[] | null;
  mentions: string[] | null;
  created_at: string | null;
  updated_at: string | null;
  published_at: string | null;
  fts: string | null;
  images_count: number | null;
  links_count: number | null;
  location_lat: number | null;
  location_lng: number | null;
};

export type PostImagesRow = {
  id: string;
  post_id: string | null;
  url: string;
  width: number | null;
  height: number | null;
  alt: string | null;
  caption: string | null;
  position: number | null;
  sha256: string | null;
};

export type PostLinksRow = {
  id: string;
  post_id: string | null;
  url: string;
  host: string | null;
  kind: string | null;
  title: string | null;
  description: string | null;
  image_url: string | null;
  site_name: string | null;
};

export type LikesRow = {
  post_id: string;
  user_id: string;
  created_at: string | null;
};

export type BookmarkFoldersRow = {
  id: string;
  user_id: string | null;
  name: string;
  created_at: string | null;
};

export type BookmarksRow = {
  user_id: string;
  post_id: string;
  folder_id: string | null;
  created_at: string | null;
};

export type SharesRow = {
  id: string;
  post_id: string | null;
  user_id: string | null;
  channel: string | null;
  created_at: string | null;
};

export type PostDailyStatsRow = {
  post_id: string;
  day: string;
  views: number | null;
  impressions: number | null;
  dwell_ms: number | null;
};

export type CommentsRow = {
  id: string;
  post_id: string | null;
  parent_id: string | null;
  author_id: string | null;
  depth: number;
  path: string;
  body_md: string;
  body_text: string | null;
  images: Json | null;
  likes_count: number | null;
  status: PostStatus;
  created_at: string | null;
  updated_at: string | null;
  fts: string | null;
};

export type CommentLikesRow = {
  comment_id: string;
  user_id: string;
  created_at: string | null;
};

export type UserEventsRow = {
  id: string;
  user_id: string | null;
  event_type: string;
  target_type: string | null;
  target_id: string | null;
  weight: number | null;
  dwell_ms: number | null;
  created_at: string | null;
};

export type ConversationsRow = {
  id: string;
  kind: ConvKind;
  title: string | null;
  avatar: string | null;
  last_message_at: string | null;
  preview: string | null;
  created_at: string | null;
};

export type ConversationMembersRow = {
  conversation_id: string;
  user_id: string;
  role: MemberRole;
  muted_until: string | null;
  archived: boolean | null;
  pinned: boolean | null;
  lock_hash: string | null;
  wallpaper: string | null;
  unread_count: number | null;
  last_read_at: string | null;
  joined_at: string | null;
};

export type MessagesRow = {
  id: string;
  conversation_id: string | null;
  sender_id: string | null;
  body_md: string | null;
  body_text: string | null;
  reply_to_id: string | null;
  attachment: Json | null;
  edited_at: string | null;
  deleted_at: string | null;
  created_at: string | null;
};

export type MessageReactionsRow = {
  message_id: string;
  user_id: string;
  emoji: string;
  created_at: string | null;
};

export type NotificationsRow = {
  id: string;
  user_id: string | null;
  type: NotificationType;
  actor_id: string | null;
  body_text: string;
  link: string | null;
  payload: Json | null;
  read_at: string | null;
  created_at: string | null;
};

export type NotificationPrefsRow = {
  user_id: string;
  prefs: Json | null;
  quiet_start: string | null;
  quiet_end: string | null;
  updated_at: string | null;
};

export type PushSubscriptionsRow = {
  id: string;
  user_id: string | null;
  endpoint: string;
  p256dh: string;
  auth: string;
  ua: string | null;
  created_at: string | null;
};

export type FcmTokensRow = {
  id: string;
  user_id: string | null;
  token: string;
  created_at: string | null;
};

export type PushOutboxRow = {
  id: string;
  user_id: string | null;
  title: string;
  body: string;
  link: string | null;
  tag: string | null;
  status: OutboxStatus;
  attempts: number | null;
  created_at: string | null;
  sent_at: string | null;
};

export type ReportsRow = {
  id: string;
  reporter_id: string | null;
  target_type: string;
  target_id: string;
  reason: string;
  status: ReportStatus;
  created_at: string | null;
  resolved_at: string | null;
  resolved_by: string | null;
};

export type ModerationActionsRow = {
  id: string;
  actor_id: string | null;
  action: string;
  target_type: string;
  target_id: string;
  reason: string | null;
  created_at: string | null;
};

export type AuditLogsRow = {
  id: string;
  actor_id: string | null;
  action: string;
  entity_type: string;
  entity_id: string;
  before: Json | null;
  after: Json | null;
  created_at: string | null;
};

export type AdminSettingsRow = {
  key: string;
  value: Json;
  updated_at: string | null;
};

export type FeatureFlagsRow = {
  key: string;
  enabled: boolean;
  description: string | null;
  updated_at: string | null;
};

export type AlgorithmWeightsRow = {
  id: number;
  w_dwell: number | null;
  w_comment: number | null;
  w_share: number | null;
  w_hide: number | null;
  w_report: number | null;
  simple_weights: Json | null;
  exploration_rate: number | null;
  decay_tau_hours: number | null;
  updated_at: string | null;
  simple_class_section: number | null;
  simple_class: number | null;
  simple_section: number | null;
  simple_location: number | null;
  simple_interaction: number | null;
  simple_interest: number | null;
};

export type BannedWordsRow = {
  word: string;
  added_at: string | null;
};

export type LinkRulesRow = {
  host: string;
  rule: string;
  created_at: string | null;
};

export type RedirectsRow = {
  from_path: string;
  to_path: string;
  code: number;
};

export type SeoOverridesRow = {
  path: string;
  title: string | null;
  description: string | null;
  canonical: string | null;
  noindex: boolean | null;
  jsonld: Json | null;
};

export type PostEmbeddingsRow = {
  post_id: string;
  vec: number[] | null;
  updated_at: string | null;
};

export type UserEmbeddingsRow = {
  user_id: string;
  vec: number[] | null;
  updated_at: string | null;
};

export type ClustersRow = {
  id: string;
  name: string;
  centroid: number[] | null;
  member_count: number | null;
  created_at: string | null;
  description: string | null;
  trending_posts: string[] | null;
  updated_at: string | null;
};

export type ClusterMembersRow = {
  cluster_id: string;
  user_id: string;
  score: number | null;
  joined_at: string | null;
};

export type AcademicYearJobsRow = {
  id: string;
  year: number;
  status: string;
  affected: number | null;
  created_at: string | null;
  completed_at: string | null;
};

export type SearchLogsRow = {
  id: string;
  user_id: string | null;
  query: string;
  results_count: number | null;
  created_at: string | null;
};

export type PageStatsRow = {
  day: string;
  path: string;
  views: number | null;
};

export type ErrorEventsRow = {
  id: string;
  user_id: string | null;
  message: string;
  stack: string | null;
  url: string | null;
  user_agent: string | null;
  created_at: string | null;
};

export type HeartbeatsRow = {
  key: string;
  at: string | null;
  meta: Json | null;
};

export type I18nStringsRow = {
  key: string;
  bn: string;
  en: string;
};

export type PushTemplatesRow = {
  key: string;
  title_bn: string;
  title_en: string;
  body_bn: string;
  body_en: string;
  link_pattern: string | null;
};

export type BadgesRow = {
  key: string;
  name_bn: string;
  name_en: string;
  icon: string | null;
  description_bn: string | null;
  description_en: string | null;
};

export type UserBadgesRow = {
  user_id: string;
  badge_key: string;
  awarded_at: string | null;
};

export type PublicAcademicsRow = {
  user_id: unknown;
  current_class: unknown;
  section: unknown;
  roll: unknown;
  academic_year: unknown;
  graduated: unknown;
};

export type UserInteractionSummaryRow = {
  user_id: unknown;
  author_id: unknown;
  interaction_count: unknown;
  affinity_score: unknown;
  last_interaction: unknown;
};

export type PostPerformanceRow = {
  id: unknown;
  author_id: unknown;
  title: unknown;
  created_at: unknown;
  likes_count: unknown;
  comments_count: unknown;
  shares_count: unknown;
  views_count: unknown;
  impressions_count: unknown;
  total_views_30d: unknown;
  total_impressions_30d: unknown;
  avg_dwell_ms: unknown;
  engagement_rate: unknown;
};

export type AuthorStatsRow = {
  author_id: unknown;
  total_posts: unknown;
  total_likes: unknown;
  total_comments: unknown;
  total_shares: unknown;
  total_views: unknown;
  avg_likes_per_post: unknown;
  avg_comments_per_post: unknown;
  last_post_date: unknown;
};

export type SearchAllResult = {
  result_type: string;
  id: string;
  title: string;
  subtitle: string;
  url: string;
  rank: number;
};

export type FeedSimpleResult = {
  post_id: string;
};

export type GetUserInteractionHistoryResult = {
  author_id: string;
  affinity_score: number;
};

export type GetTrendingInClusterResult = {
  post_id: string;
  score: number;
};

export type GetColdStartPostsResult = {
  post_id: string;
  author_id: string;
};

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: ProfilesRow;
        Insert: {
          id: string;
          handle: string;
          full_name: string;
          email: string;
          role?: UserRole;
          status?: AppStatus;
          avatar_url?: string | null;
          banner_url?: string | null;
          bio?: string | null;
          website_url?: string | null;
          location_text?: string | null;
          lat?: number | null;
          lng?: number | null;
          location_consent?: boolean | null;
          notif_consent?: boolean | null;
          theme_accent?: string | null;
          pronouns?: string | null;
          verified?: boolean | null;
          onboarded?: boolean | null;
          interests?: string[] | null;
          show_dwell?: boolean | null;
          locale?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          handle?: string;
          full_name?: string;
          email?: string;
          role?: UserRole;
          status?: AppStatus;
          avatar_url?: string | null;
          banner_url?: string | null;
          bio?: string | null;
          website_url?: string | null;
          location_text?: string | null;
          lat?: number | null;
          lng?: number | null;
          location_consent?: boolean | null;
          notif_consent?: boolean | null;
          theme_accent?: string | null;
          pronouns?: string | null;
          verified?: boolean | null;
          onboarded?: boolean | null;
          interests?: string[] | null;
          show_dwell?: boolean | null;
          locale?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [
        ];
      };
      reserved_handles: {
        Row: ReservedHandlesRow;
        Insert: {
          handle: string;
        };
        Update: {
          handle?: string;
        };
        Relationships: [
        ];
      };
      academics: {
        Row: AcademicsRow;
        Insert: {
          user_id: string;
          current_class: number;
          section?: string | null;
          roll?: number | null;
          academic_year?: number;
          nid_or_brc?: string | null;
          dob?: string | null;
          needs_year_update?: boolean | null;
          graduated?: boolean | null;
          history?: Json | null;
        };
        Update: {
          user_id?: string;
          current_class?: number;
          section?: string | null;
          roll?: number | null;
          academic_year?: number;
          nid_or_brc?: string | null;
          dob?: string | null;
          needs_year_update?: boolean | null;
          graduated?: boolean | null;
          history?: Json | null;
        };
        Relationships: [
          { foreignKeyName: 'academics_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      teacher_info: {
        Row: TeacherInfoRow;
        Insert: {
          user_id: string;
          experience_years?: number | null;
          teaches?: Json | null;
          department?: string | null;
        };
        Update: {
          user_id?: string;
          experience_years?: number | null;
          teaches?: Json | null;
          department?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'teacher_info_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      alumni_info: {
        Row: AlumniInfoRow;
        Insert: {
          user_id: string;
          current_institution?: string | null;
          current_class?: string | null;
          old_class?: number | null;
          old_section?: string | null;
          old_roll?: number | null;
          passing_year?: number | null;
          notes?: string | null;
        };
        Update: {
          user_id?: string;
          current_institution?: string | null;
          current_class?: string | null;
          old_class?: number | null;
          old_section?: string | null;
          old_roll?: number | null;
          passing_year?: number | null;
          notes?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'alumni_info_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      guardian_info: {
        Row: GuardianInfoRow;
        Insert: {
          user_id: string;
          phone?: string | null;
          relationship: string;
          occupation?: string | null;
        };
        Update: {
          user_id?: string;
          phone?: string | null;
          relationship?: string;
          occupation?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'guardian_info_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      guardian_children: {
        Row: GuardianChildrenRow;
        Insert: {
          guardian_id: string;
          child_id: string;
          status?: ChildLinkStatus;
          created_at?: string | null;
        };
        Update: {
          guardian_id?: string;
          child_id?: string;
          status?: ChildLinkStatus;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'guardian_children_guardian_id_fkey'; columns: ['guardian_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'guardian_children_child_id_fkey'; columns: ['child_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      class_sections: {
        Row: ClassSectionsRow;
        Insert: {
          academic_year: number;
          class_no: number;
          section: string;
        };
        Update: {
          academic_year?: number;
          class_no?: number;
          section?: string;
        };
        Relationships: [
        ];
      };
      registration_applications: {
        Row: RegistrationApplicationsRow;
        Insert: {
          id?: string;
          applicant_id?: string | null;
          role: UserRole;
          payload: Json;
          status?: AppStatus;
          attempt?: number | null;
          submitted_at?: string | null;
          decided_at?: string | null;
          decided_by?: string | null;
          reason?: string | null;
        };
        Update: {
          id?: string;
          applicant_id?: string | null;
          role?: UserRole;
          payload?: Json;
          status?: AppStatus;
          attempt?: number | null;
          submitted_at?: string | null;
          decided_at?: string | null;
          decided_by?: string | null;
          reason?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'registration_applications_decided_by_fkey'; columns: ['decided_by']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      approval_events: {
        Row: ApprovalEventsRow;
        Insert: {
          id?: string;
          application_id?: string | null;
          actor_id?: string | null;
          action: string;
          note?: string | null;
          ts?: string | null;
        };
        Update: {
          id?: string;
          application_id?: string | null;
          actor_id?: string | null;
          action?: string;
          note?: string | null;
          ts?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'approval_events_application_id_fkey'; columns: ['application_id']; isOneToOne: false; referencedRelation: 'registration_applications'; referencedColumns: ['id'] },
          { foreignKeyName: 'approval_events_actor_id_fkey'; columns: ['actor_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      secure_documents: {
        Row: SecureDocumentsRow;
        Insert: {
          id?: string;
          owner_id?: string | null;
          purpose: string;
          mime_original: string;
          sha256: string;
          svg_text: string;
          size_bytes: number;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string | null;
          purpose?: string;
          mime_original?: string;
          sha256?: string;
          svg_text?: string;
          size_bytes?: number;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'secure_documents_owner_id_fkey'; columns: ['owner_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      follows: {
        Row: FollowsRow;
        Insert: {
          follower_id: string;
          following_id: string;
          created_at?: string | null;
        };
        Update: {
          follower_id?: string;
          following_id?: string;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'follows_follower_id_fkey'; columns: ['follower_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'follows_following_id_fkey'; columns: ['following_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      blocks: {
        Row: BlocksRow;
        Insert: {
          blocker_id: string;
          blocked_id: string;
          created_at?: string | null;
        };
        Update: {
          blocker_id?: string;
          blocked_id?: string;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'blocks_blocker_id_fkey'; columns: ['blocker_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'blocks_blocked_id_fkey'; columns: ['blocked_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      muted_users: {
        Row: MutedUsersRow;
        Insert: {
          muter_id: string;
          muted_id: string;
          created_at?: string | null;
        };
        Update: {
          muter_id?: string;
          muted_id?: string;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'muted_users_muter_id_fkey'; columns: ['muter_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'muted_users_muted_id_fkey'; columns: ['muted_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      hidden_posts: {
        Row: HiddenPostsRow;
        Insert: {
          user_id: string;
          post_id: string;
          created_at?: string | null;
        };
        Update: {
          user_id?: string;
          post_id?: string;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'hidden_posts_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      posts: {
        Row: PostsRow;
        Insert: {
          id?: string;
          author_id?: string | null;
          type?: PostType;
          title?: string | null;
          body_md?: string | null;
          body_text?: string | null;
          slug?: string | null;
          class_tag?: number | null;
          section_tag?: string | null;
          location?: string | null;
          language?: string | null;
          comments_enabled?: boolean | null;
          sensitive?: boolean | null;
          pinned?: boolean | null;
          status?: PostStatus;
          likes_count?: number | null;
          comments_count?: number | null;
          shares_count?: number | null;
          views_count?: number | null;
          impressions_count?: number | null;
          hashtags?: string[] | null;
          mentions?: string[] | null;
          created_at?: string | null;
          updated_at?: string | null;
          published_at?: string | null;
          images_count?: number | null;
          links_count?: number | null;
          location_lat?: number | null;
          location_lng?: number | null;
        };
        Update: {
          id?: string;
          author_id?: string | null;
          type?: PostType;
          title?: string | null;
          body_md?: string | null;
          body_text?: string | null;
          slug?: string | null;
          class_tag?: number | null;
          section_tag?: string | null;
          location?: string | null;
          language?: string | null;
          comments_enabled?: boolean | null;
          sensitive?: boolean | null;
          pinned?: boolean | null;
          status?: PostStatus;
          likes_count?: number | null;
          comments_count?: number | null;
          shares_count?: number | null;
          views_count?: number | null;
          impressions_count?: number | null;
          hashtags?: string[] | null;
          mentions?: string[] | null;
          created_at?: string | null;
          updated_at?: string | null;
          published_at?: string | null;
          images_count?: number | null;
          links_count?: number | null;
          location_lat?: number | null;
          location_lng?: number | null;
        };
        Relationships: [
          { foreignKeyName: 'posts_author_id_fkey'; columns: ['author_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      post_images: {
        Row: PostImagesRow;
        Insert: {
          id?: string;
          post_id?: string | null;
          url: string;
          width?: number | null;
          height?: number | null;
          alt?: string | null;
          caption?: string | null;
          position?: number | null;
          sha256?: string | null;
        };
        Update: {
          id?: string;
          post_id?: string | null;
          url?: string;
          width?: number | null;
          height?: number | null;
          alt?: string | null;
          caption?: string | null;
          position?: number | null;
          sha256?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'post_images_post_id_fkey'; columns: ['post_id']; isOneToOne: false; referencedRelation: 'posts'; referencedColumns: ['id'] },
        ];
      };
      post_links: {
        Row: PostLinksRow;
        Insert: {
          id?: string;
          post_id?: string | null;
          url: string;
          host?: string | null;
          kind?: string | null;
          title?: string | null;
          description?: string | null;
          image_url?: string | null;
          site_name?: string | null;
        };
        Update: {
          id?: string;
          post_id?: string | null;
          url?: string;
          host?: string | null;
          kind?: string | null;
          title?: string | null;
          description?: string | null;
          image_url?: string | null;
          site_name?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'post_links_post_id_fkey'; columns: ['post_id']; isOneToOne: false; referencedRelation: 'posts'; referencedColumns: ['id'] },
        ];
      };
      likes: {
        Row: LikesRow;
        Insert: {
          post_id: string;
          user_id: string;
          created_at?: string | null;
        };
        Update: {
          post_id?: string;
          user_id?: string;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'likes_post_id_fkey'; columns: ['post_id']; isOneToOne: false; referencedRelation: 'posts'; referencedColumns: ['id'] },
          { foreignKeyName: 'likes_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      bookmark_folders: {
        Row: BookmarkFoldersRow;
        Insert: {
          id?: string;
          user_id?: string | null;
          name: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          name?: string;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'bookmark_folders_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      bookmarks: {
        Row: BookmarksRow;
        Insert: {
          user_id: string;
          post_id: string;
          folder_id?: string | null;
          created_at?: string | null;
        };
        Update: {
          user_id?: string;
          post_id?: string;
          folder_id?: string | null;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'bookmarks_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'bookmarks_post_id_fkey'; columns: ['post_id']; isOneToOne: false; referencedRelation: 'posts'; referencedColumns: ['id'] },
          { foreignKeyName: 'bookmarks_folder_id_fkey'; columns: ['folder_id']; isOneToOne: false; referencedRelation: 'bookmark_folders'; referencedColumns: ['id'] },
        ];
      };
      shares: {
        Row: SharesRow;
        Insert: {
          id?: string;
          post_id?: string | null;
          user_id?: string | null;
          channel?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          post_id?: string | null;
          user_id?: string | null;
          channel?: string | null;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'shares_post_id_fkey'; columns: ['post_id']; isOneToOne: false; referencedRelation: 'posts'; referencedColumns: ['id'] },
          { foreignKeyName: 'shares_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      post_daily_stats: {
        Row: PostDailyStatsRow;
        Insert: {
          post_id: string;
          day: string;
          views?: number | null;
          impressions?: number | null;
          dwell_ms?: number | null;
        };
        Update: {
          post_id?: string;
          day?: string;
          views?: number | null;
          impressions?: number | null;
          dwell_ms?: number | null;
        };
        Relationships: [
          { foreignKeyName: 'post_daily_stats_post_id_fkey'; columns: ['post_id']; isOneToOne: false; referencedRelation: 'posts'; referencedColumns: ['id'] },
        ];
      };
      comments: {
        Row: CommentsRow;
        Insert: {
          id?: string;
          post_id?: string | null;
          parent_id?: string | null;
          author_id?: string | null;
          depth: number;
          path: string;
          body_md: string;
          body_text?: string | null;
          images?: Json | null;
          likes_count?: number | null;
          status?: PostStatus;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          post_id?: string | null;
          parent_id?: string | null;
          author_id?: string | null;
          depth?: number;
          path?: string;
          body_md?: string;
          body_text?: string | null;
          images?: Json | null;
          likes_count?: number | null;
          status?: PostStatus;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'comments_post_id_fkey'; columns: ['post_id']; isOneToOne: false; referencedRelation: 'posts'; referencedColumns: ['id'] },
          { foreignKeyName: 'comments_parent_id_fkey'; columns: ['parent_id']; isOneToOne: false; referencedRelation: 'comments'; referencedColumns: ['id'] },
          { foreignKeyName: 'comments_author_id_fkey'; columns: ['author_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      comment_likes: {
        Row: CommentLikesRow;
        Insert: {
          comment_id: string;
          user_id: string;
          created_at?: string | null;
        };
        Update: {
          comment_id?: string;
          user_id?: string;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'comment_likes_comment_id_fkey'; columns: ['comment_id']; isOneToOne: false; referencedRelation: 'comments'; referencedColumns: ['id'] },
          { foreignKeyName: 'comment_likes_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      user_events: {
        Row: UserEventsRow;
        Insert: {
          id?: string;
          user_id?: string | null;
          event_type: string;
          target_type?: string | null;
          target_id?: string | null;
          weight?: number | null;
          dwell_ms?: number | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          event_type?: string;
          target_type?: string | null;
          target_id?: string | null;
          weight?: number | null;
          dwell_ms?: number | null;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'user_events_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      conversations: {
        Row: ConversationsRow;
        Insert: {
          id?: string;
          kind?: ConvKind;
          title?: string | null;
          avatar?: string | null;
          last_message_at?: string | null;
          preview?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          kind?: ConvKind;
          title?: string | null;
          avatar?: string | null;
          last_message_at?: string | null;
          preview?: string | null;
          created_at?: string | null;
        };
        Relationships: [
        ];
      };
      conversation_members: {
        Row: ConversationMembersRow;
        Insert: {
          conversation_id: string;
          user_id: string;
          role?: MemberRole;
          muted_until?: string | null;
          archived?: boolean | null;
          pinned?: boolean | null;
          lock_hash?: string | null;
          wallpaper?: string | null;
          unread_count?: number | null;
          last_read_at?: string | null;
          joined_at?: string | null;
        };
        Update: {
          conversation_id?: string;
          user_id?: string;
          role?: MemberRole;
          muted_until?: string | null;
          archived?: boolean | null;
          pinned?: boolean | null;
          lock_hash?: string | null;
          wallpaper?: string | null;
          unread_count?: number | null;
          last_read_at?: string | null;
          joined_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'conversation_members_conversation_id_fkey'; columns: ['conversation_id']; isOneToOne: false; referencedRelation: 'conversations'; referencedColumns: ['id'] },
          { foreignKeyName: 'conversation_members_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      messages: {
        Row: MessagesRow;
        Insert: {
          id?: string;
          conversation_id?: string | null;
          sender_id?: string | null;
          body_md?: string | null;
          body_text?: string | null;
          reply_to_id?: string | null;
          attachment?: Json | null;
          edited_at?: string | null;
          deleted_at?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          conversation_id?: string | null;
          sender_id?: string | null;
          body_md?: string | null;
          body_text?: string | null;
          reply_to_id?: string | null;
          attachment?: Json | null;
          edited_at?: string | null;
          deleted_at?: string | null;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'messages_conversation_id_fkey'; columns: ['conversation_id']; isOneToOne: false; referencedRelation: 'conversations'; referencedColumns: ['id'] },
          { foreignKeyName: 'messages_sender_id_fkey'; columns: ['sender_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'messages_reply_to_id_fkey'; columns: ['reply_to_id']; isOneToOne: false; referencedRelation: 'messages'; referencedColumns: ['id'] },
        ];
      };
      message_reactions: {
        Row: MessageReactionsRow;
        Insert: {
          message_id: string;
          user_id: string;
          emoji: string;
          created_at?: string | null;
        };
        Update: {
          message_id?: string;
          user_id?: string;
          emoji?: string;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'message_reactions_message_id_fkey'; columns: ['message_id']; isOneToOne: false; referencedRelation: 'messages'; referencedColumns: ['id'] },
          { foreignKeyName: 'message_reactions_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      notifications: {
        Row: NotificationsRow;
        Insert: {
          id?: string;
          user_id?: string | null;
          type: NotificationType;
          actor_id?: string | null;
          body_text: string;
          link?: string | null;
          payload?: Json | null;
          read_at?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          type?: NotificationType;
          actor_id?: string | null;
          body_text?: string;
          link?: string | null;
          payload?: Json | null;
          read_at?: string | null;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'notifications_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'notifications_actor_id_fkey'; columns: ['actor_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      notification_prefs: {
        Row: NotificationPrefsRow;
        Insert: {
          user_id: string;
          prefs?: Json | null;
          quiet_start?: string | null;
          quiet_end?: string | null;
          updated_at?: string | null;
        };
        Update: {
          user_id?: string;
          prefs?: Json | null;
          quiet_start?: string | null;
          quiet_end?: string | null;
          updated_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'notification_prefs_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      push_subscriptions: {
        Row: PushSubscriptionsRow;
        Insert: {
          id?: string;
          user_id?: string | null;
          endpoint: string;
          p256dh: string;
          auth: string;
          ua?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          endpoint?: string;
          p256dh?: string;
          auth?: string;
          ua?: string | null;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'push_subscriptions_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      fcm_tokens: {
        Row: FcmTokensRow;
        Insert: {
          id?: string;
          user_id?: string | null;
          token: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          token?: string;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'fcm_tokens_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      push_outbox: {
        Row: PushOutboxRow;
        Insert: {
          id?: string;
          user_id?: string | null;
          title: string;
          body: string;
          link?: string | null;
          tag?: string | null;
          status?: OutboxStatus;
          attempts?: number | null;
          created_at?: string | null;
          sent_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          title?: string;
          body?: string;
          link?: string | null;
          tag?: string | null;
          status?: OutboxStatus;
          attempts?: number | null;
          created_at?: string | null;
          sent_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'push_outbox_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      reports: {
        Row: ReportsRow;
        Insert: {
          id?: string;
          reporter_id?: string | null;
          target_type: string;
          target_id: string;
          reason: string;
          status?: ReportStatus;
          created_at?: string | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
        };
        Update: {
          id?: string;
          reporter_id?: string | null;
          target_type?: string;
          target_id?: string;
          reason?: string;
          status?: ReportStatus;
          created_at?: string | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'reports_reporter_id_fkey'; columns: ['reporter_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'reports_resolved_by_fkey'; columns: ['resolved_by']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      moderation_actions: {
        Row: ModerationActionsRow;
        Insert: {
          id?: string;
          actor_id?: string | null;
          action: string;
          target_type: string;
          target_id: string;
          reason?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          actor_id?: string | null;
          action?: string;
          target_type?: string;
          target_id?: string;
          reason?: string | null;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'moderation_actions_actor_id_fkey'; columns: ['actor_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      audit_logs: {
        Row: AuditLogsRow;
        Insert: {
          id?: string;
          actor_id?: string | null;
          action: string;
          entity_type: string;
          entity_id: string;
          before?: Json | null;
          after?: Json | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          actor_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string;
          before?: Json | null;
          after?: Json | null;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'audit_logs_actor_id_fkey'; columns: ['actor_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      admin_settings: {
        Row: AdminSettingsRow;
        Insert: {
          key: string;
          value: Json;
          updated_at?: string | null;
        };
        Update: {
          key?: string;
          value?: Json;
          updated_at?: string | null;
        };
        Relationships: [
        ];
      };
      feature_flags: {
        Row: FeatureFlagsRow;
        Insert: {
          key: string;
          enabled?: boolean;
          description?: string | null;
          updated_at?: string | null;
        };
        Update: {
          key?: string;
          enabled?: boolean;
          description?: string | null;
          updated_at?: string | null;
        };
        Relationships: [
        ];
      };
      algorithm_weights: {
        Row: AlgorithmWeightsRow;
        Insert: {
          id: number;
          w_dwell?: number | null;
          w_comment?: number | null;
          w_share?: number | null;
          w_hide?: number | null;
          w_report?: number | null;
          simple_weights?: Json | null;
          exploration_rate?: number | null;
          decay_tau_hours?: number | null;
          updated_at?: string | null;
          simple_class_section?: number | null;
          simple_class?: number | null;
          simple_section?: number | null;
          simple_location?: number | null;
          simple_interaction?: number | null;
          simple_interest?: number | null;
        };
        Update: {
          id?: number;
          w_dwell?: number | null;
          w_comment?: number | null;
          w_share?: number | null;
          w_hide?: number | null;
          w_report?: number | null;
          simple_weights?: Json | null;
          exploration_rate?: number | null;
          decay_tau_hours?: number | null;
          updated_at?: string | null;
          simple_class_section?: number | null;
          simple_class?: number | null;
          simple_section?: number | null;
          simple_location?: number | null;
          simple_interaction?: number | null;
          simple_interest?: number | null;
        };
        Relationships: [
        ];
      };
      banned_words: {
        Row: BannedWordsRow;
        Insert: {
          word: string;
          added_at?: string | null;
        };
        Update: {
          word?: string;
          added_at?: string | null;
        };
        Relationships: [
        ];
      };
      link_rules: {
        Row: LinkRulesRow;
        Insert: {
          host: string;
          rule: string;
          created_at?: string | null;
        };
        Update: {
          host?: string;
          rule?: string;
          created_at?: string | null;
        };
        Relationships: [
        ];
      };
      redirects: {
        Row: RedirectsRow;
        Insert: {
          from_path: string;
          to_path: string;
          code?: number;
        };
        Update: {
          from_path?: string;
          to_path?: string;
          code?: number;
        };
        Relationships: [
        ];
      };
      seo_overrides: {
        Row: SeoOverridesRow;
        Insert: {
          path: string;
          title?: string | null;
          description?: string | null;
          canonical?: string | null;
          noindex?: boolean | null;
          jsonld?: Json | null;
        };
        Update: {
          path?: string;
          title?: string | null;
          description?: string | null;
          canonical?: string | null;
          noindex?: boolean | null;
          jsonld?: Json | null;
        };
        Relationships: [
        ];
      };
      post_embeddings: {
        Row: PostEmbeddingsRow;
        Insert: {
          post_id: string;
          vec?: number[] | null;
          updated_at?: string | null;
        };
        Update: {
          post_id?: string;
          vec?: number[] | null;
          updated_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'post_embeddings_post_id_fkey'; columns: ['post_id']; isOneToOne: false; referencedRelation: 'posts'; referencedColumns: ['id'] },
        ];
      };
      user_embeddings: {
        Row: UserEmbeddingsRow;
        Insert: {
          user_id: string;
          vec?: number[] | null;
          updated_at?: string | null;
        };
        Update: {
          user_id?: string;
          vec?: number[] | null;
          updated_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'user_embeddings_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      clusters: {
        Row: ClustersRow;
        Insert: {
          id?: string;
          name: string;
          centroid?: number[] | null;
          member_count?: number | null;
          created_at?: string | null;
          description?: string | null;
          trending_posts?: string[] | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          centroid?: number[] | null;
          member_count?: number | null;
          created_at?: string | null;
          description?: string | null;
          trending_posts?: string[] | null;
          updated_at?: string | null;
        };
        Relationships: [
        ];
      };
      cluster_members: {
        Row: ClusterMembersRow;
        Insert: {
          cluster_id: string;
          user_id: string;
          score?: number | null;
          joined_at?: string | null;
        };
        Update: {
          cluster_id?: string;
          user_id?: string;
          score?: number | null;
          joined_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'cluster_members_cluster_id_fkey'; columns: ['cluster_id']; isOneToOne: false; referencedRelation: 'clusters'; referencedColumns: ['id'] },
          { foreignKeyName: 'cluster_members_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      academic_year_jobs: {
        Row: AcademicYearJobsRow;
        Insert: {
          id?: string;
          year: number;
          status: string;
          affected?: number | null;
          created_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          year?: number;
          status?: string;
          affected?: number | null;
          created_at?: string | null;
          completed_at?: string | null;
        };
        Relationships: [
        ];
      };
      search_logs: {
        Row: SearchLogsRow;
        Insert: {
          id?: string;
          user_id?: string | null;
          query: string;
          results_count?: number | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          query?: string;
          results_count?: number | null;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'search_logs_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      page_stats: {
        Row: PageStatsRow;
        Insert: {
          day: string;
          path: string;
          views?: number | null;
        };
        Update: {
          day?: string;
          path?: string;
          views?: number | null;
        };
        Relationships: [
        ];
      };
      error_events: {
        Row: ErrorEventsRow;
        Insert: {
          id?: string;
          user_id?: string | null;
          message: string;
          stack?: string | null;
          url?: string | null;
          user_agent?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          message?: string;
          stack?: string | null;
          url?: string | null;
          user_agent?: string | null;
          created_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'error_events_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
        ];
      };
      heartbeats: {
        Row: HeartbeatsRow;
        Insert: {
          key: string;
          at?: string | null;
          meta?: Json | null;
        };
        Update: {
          key?: string;
          at?: string | null;
          meta?: Json | null;
        };
        Relationships: [
        ];
      };
      i18n_strings: {
        Row: I18nStringsRow;
        Insert: {
          key: string;
          bn: string;
          en: string;
        };
        Update: {
          key?: string;
          bn?: string;
          en?: string;
        };
        Relationships: [
        ];
      };
      push_templates: {
        Row: PushTemplatesRow;
        Insert: {
          key: string;
          title_bn: string;
          title_en: string;
          body_bn: string;
          body_en: string;
          link_pattern?: string | null;
        };
        Update: {
          key?: string;
          title_bn?: string;
          title_en?: string;
          body_bn?: string;
          body_en?: string;
          link_pattern?: string | null;
        };
        Relationships: [
        ];
      };
      badges: {
        Row: BadgesRow;
        Insert: {
          key: string;
          name_bn: string;
          name_en: string;
          icon?: string | null;
          description_bn?: string | null;
          description_en?: string | null;
        };
        Update: {
          key?: string;
          name_bn?: string;
          name_en?: string;
          icon?: string | null;
          description_bn?: string | null;
          description_en?: string | null;
        };
        Relationships: [
        ];
      };
      user_badges: {
        Row: UserBadgesRow;
        Insert: {
          user_id: string;
          badge_key: string;
          awarded_at?: string | null;
        };
        Update: {
          user_id?: string;
          badge_key?: string;
          awarded_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: 'user_badges_user_id_fkey'; columns: ['user_id']; isOneToOne: false; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'user_badges_badge_key_fkey'; columns: ['badge_key']; isOneToOne: false; referencedRelation: 'badges'; referencedColumns: ['key'] },
        ];
      };
    };
    Views: {
      public_academics: {
        Row: PublicAcademicsRow;
        Relationships: [];
      };
      user_interaction_summary: {
        Row: UserInteractionSummaryRow;
        Relationships: [];
      };
      post_performance: {
        Row: PostPerformanceRow;
        Relationships: [];
      };
      author_stats: {
        Row: AuthorStatsRow;
        Relationships: [];
      };
    };
    Functions: {
      update_updated_at: { Args: Record<string, never>; Returns: unknown };
      strip_markdown: { Args: { md: string | null }; Returns: string };
      extract_hashtags: { Args: { text_input: string | null }; Returns: unknown };
      extract_mentions: { Args: { text_input: string | null }; Returns: unknown };
      is_admin: { Args: Record<string, never>; Returns: boolean };
      is_approved: { Args: Record<string, never>; Returns: boolean };
      process_post_body: { Args: Record<string, never>; Returns: unknown };
      generate_post_slug: { Args: Record<string, never>; Returns: unknown };
      update_post_likes_count: { Args: Record<string, never>; Returns: unknown };
      update_post_comments_count: { Args: Record<string, never>; Returns: unknown };
      update_post_shares_count: { Args: Record<string, never>; Returns: unknown };
      process_comment_body: { Args: Record<string, never>; Returns: unknown };
      update_comment_likes_count: { Args: Record<string, never>; Returns: unknown };
      validate_handle_not_reserved: { Args: Record<string, never>; Returns: unknown };
      guard_privilege_escalation: { Args: Record<string, never>; Returns: unknown };
      guard_secure_documents_immutability: { Args: Record<string, never>; Returns: unknown };
      guard_follow_block: { Args: Record<string, never>; Returns: unknown };
      notify_user: { Args: { p_user_id: string | null; p_type: NotificationType | null; p_actor_id: string | null; p_body_text: string | null; p_link: string | null; p_payload?: Json | null }; Returns: undefined };
      enqueue_push_notification: { Args: Record<string, never>; Returns: unknown };
      process_message_body: { Args: Record<string, never>; Returns: unknown };
      update_conversation_preview: { Args: Record<string, never>; Returns: unknown };
      submit_application: { Args: { p_role: UserRole | null; p_payload: Json | null }; Returns: string };
      decide_application: { Args: { p_app_id: string | null; p_approve: boolean | null; p_reason?: string | null; p_edits?: Json | null }; Returns: undefined };
      follow_user: { Args: { p_following_id: string | null }; Returns: undefined };
      unfollow_user: { Args: { p_following_id: string | null }; Returns: undefined };
      like_post: { Args: { p_post_id: string | null }; Returns: undefined };
      unlike_post: { Args: { p_post_id: string | null }; Returns: undefined };
      add_comment: { Args: { p_post_id: string | null; p_parent_id: string | null; p_body: string | null; p_images?: Json | null }; Returns: string };
      increment_post_stats: { Args: { p_post_id: string | null; p_views?: number | null; p_impressions?: number | null; p_dwell_ms?: number | null }; Returns: undefined };
      log_event: { Args: { p_event_type: string | null; p_target_type?: string | null; p_target_id?: string | null; p_weight?: number | null; p_dwell_ms?: number | null }; Returns: undefined };
      get_or_create_dm: { Args: { p_other_user_id: string | null }; Returns: string };
      send_message: { Args: { p_conv_id: string | null; p_body: string | null; p_reply_to_id?: string | null; p_attachment?: Json | null }; Returns: string };
      mark_conversation_read: { Args: { p_conv_id: string | null }; Returns: undefined };
      react_to_message: { Args: { p_message_id: string | null; p_emoji: string | null }; Returns: undefined };
      register_push_subscription: { Args: { p_endpoint: string | null; p_p256dh: string | null; p_auth: string | null; p_ua?: string | null }; Returns: undefined };
      remove_push_subscription: { Args: { p_endpoint: string | null }; Returns: undefined };
      enqueue_push: { Args: { p_user_id: string | null; p_title: string | null; p_body: string | null; p_link?: string | null; p_tag?: string | null }; Returns: undefined };
      promote_academic_year: { Args: { p_year: number | null }; Returns: undefined };
      confirm_year_update: { Args: { p_class: number | null; p_section: string | null; p_roll: number | null }; Returns: undefined };
      record_profile_view: { Args: { p_viewed_user_id: string | null }; Returns: undefined };
      search_all: { Args: { p_query: string | null; p_limit?: number | null }; Returns: SearchAllResult[] };
      feed_simple: { Args: { p_viewer: string | null; p_limit?: number | null; p_offset?: number | null; p_lat?: number | null; p_lng?: number | null }; Returns: FeedSimpleResult[] };
      purge_old_user_events: { Args: Record<string, never>; Returns: number };
      get_user_interaction_history: { Args: { p_user_id: string | null }; Returns: GetUserInteractionHistoryResult[] };
      get_trending_in_cluster: { Args: { p_cluster_id: string | null; p_limit?: number | null }; Returns: GetTrendingInClusterResult[] };
      update_cluster_trending: { Args: Record<string, never>; Returns: number };
      get_cold_start_posts: { Args: { p_limit?: number | null }; Returns: GetColdStartPostsResult[] };
      log_dwell_time: { Args: { p_post_id: string | null; p_dwell_ms: number | null }; Returns: undefined };
      update_post_images_count: { Args: Record<string, never>; Returns: unknown };
      update_post_links_count: { Args: Record<string, never>; Returns: unknown };
      purge_old_events: { Args: Record<string, never>; Returns: number };
      update_cluster_memberships: { Args: Record<string, never>; Returns: number };
    };
    Enums: {
      user_role: UserRole;
      app_status: AppStatus;
      post_type: PostType;
      post_status: PostStatus;
      notification_type: NotificationType;
      report_status: ReportStatus;
      conv_kind: ConvKind;
      member_role: MemberRole;
      outbox_status: OutboxStatus;
      child_link_status: ChildLinkStatus;
    };
    CompositeTypes: { [_ in never]: never };
  };
};

// --- App-facing aliases ----------------------------------------------------

export type Profile = ProfilesRow;
export type Post = PostsRow;
export type Comment = CommentsRow;
export type Like = LikesRow;
export type Follow = FollowsRow;
export type Message = MessagesRow;
export type Conversation = ConversationsRow;
export type Notification = NotificationsRow;
export type RegistrationApplication = RegistrationApplicationsRow;
export type PostImage = PostImagesRow;
export type PostLink = PostLinksRow;
export type Academic = AcademicsRow;
export type PushSubscription = PushSubscriptionsRow;
export type PushOutboxItem = PushOutboxRow;
export type PublicAcademics = PublicAcademicsRow;
export type SearchResult = SearchAllResult;

/**
 * A post with its author, and optionally its inline media.
 *
 * These are type aliases (not interfaces): supabase-js checks
 * `Row extends Record<string, unknown>`, and only object *type aliases* get
 * an implicit index signature. Using `interface` silently collapses the whole
 * schema to `never`.
 */
export type PostWithAuthor = PostsRow & {
  author: ProfilesRow;
  images?: PostImagesRow[];
  links?: PostLinksRow[];
};

/** A comment with its author and, when threaded, its replies. */
export type CommentWithAuthor = CommentsRow & {
  author: ProfilesRow;
  replies?: CommentWithAuthor[];
};
